/**
 * Neutral report skeleton — the fail-closed replacement for the old mock base.
 *
 * Every value is either honestly empty (zeros, empty arrays, "—"/"Unknown") or
 * flagged `isPlaceholder: true`. Nothing here is fabricated: no invented
 * headlines, no pseudo-random financials, no fake company profiles. Live
 * provider data overwrites these fields in buildReport; whatever a provider
 * does not supply stays visibly empty instead of plausibly wrong.
 */

const DISCLAIMER =
  "This report is generated by FinDesk AI and is for informational and research support purposes only. It does not constitute licensed financial advice, a solicitation to buy or sell any security, or a guarantee of future performance. Always conduct your own due diligence before making investment decisions.";

const NO_DATA = "No live provider data for this section.";

export function neutralBaseReport(ticker: string, id: number) {
  const tickerUpper = ticker.toUpperCase();
  return {
    id,
    ticker: tickerUpper,
    companyName: tickerUpper,
    sector: "Unknown",
    industry: "Unknown",
    generatedAt: new Date().toISOString(),
    // WATCH = "not rated": no provider produced a verdict. Never BUY/SELL/HOLD by default.
    overallRating: "WATCH" as string,
    disclaimer: DISCLAIMER,
    snapshot: {
      description: NO_DATA,
      marketCap: "—",
      price: 0,
      change1d: 0,
      change52w: 0,
      peRatio: 0,
      eps: 0,
      revenue: "—",
      employees: "—",
      headquarters: "—",
      founded: "—",
      exchange: "—",
    },
    catalysts: {
      positive: [] as string[],
      negative: [] as string[],
      upcoming: [] as string[],
    },
    news: {
      isPlaceholder: true,
      sentiment: "Neutral" as string,
      headlines: [] as Array<{ title: string; source: string; date: string | undefined; sentiment: string }>,
    },
    filings: {
      isPlaceholder: true,
      lastForm10K: "",
      lastForm10Q: "",
      keyHighlights: [] as string[],
    },
    financials: {
      isPlaceholder: true,
      revenueGrowthYoY: 0,
      grossMargin: 0,
      operatingMargin: 0,
      netMargin: 0,
      debtToEquity: 0,
      currentRatio: 0,
      freeCashFlow: "—",
      revenueHistory: [] as Array<{ period: string; revenue: number }>,
    },
    valuation: {
      isPlaceholder: true,
      currentPrice: 0,
      intrinsicValueLow: 0,
      intrinsicValueHigh: 0,
      peComparison: NO_DATA,
      evEbitda: 0,
      priceToBook: 0,
      priceToSales: 0,
      dcfNotes: NO_DATA,
      comparables: [] as Array<{ ticker: string; pe: number; evEbitda: number }>,
    },
    technical: {
      isPlaceholder: true,
      trend: "Unknown" as string,
      rsi: 0,
      macd: "Unknown" as string,
      supportLevel: 0,
      resistanceLevel: 0,
      ma50: 0,
      ma200: 0,
      goldenCross: false,
      notes: NO_DATA,
    },
    risks: {
      items: [] as Array<{ category: string; description: string; severity: string }>,
    },
    thesis: {
      bull: { targetPrice: 0, probability: 0, summary: NO_DATA, points: [] as string[] },
      base: { targetPrice: 0, probability: 0, summary: NO_DATA, points: [] as string[] },
      bear: { targetPrice: 0, probability: 0, summary: NO_DATA, points: [] as string[] },
    },
    actionPlan: {
      rating: "WATCH" as string,
      rationale:
        "No actionable rating: insufficient live provider data to form a verdict.",
      positionSizing:
        "Research framework suggests sizing consistent with position conviction and individual portfolio risk tolerance. This model does not prescribe specific portfolio weights.",
      entryZone: "—",
      stopLoss: "—",
      profitTarget: "—",
      timeHorizon: "—",
      keyMonitors: [] as string[],
      disclaimer:
        "This action plan is a research framework, not personalized financial advice. FinDesk is not a licensed investment adviser. The entry zones, stop losses, and targets above are analytical reference points only — not recommendations. Consult a qualified financial professional before making any investment decisions.",
    },
  };
}
