import { GetReportResponse, type Report as FullReport } from "@workspace/api-zod";
import type { MarketData } from "./marketData.js";
import type { AiReportOutput } from "./aiReport.js";

const DISCLAIMER =
  "This report is generated by FinDesk AI and is for informational and research support purposes only. It does not constitute licensed financial advice, a solicitation to buy or sell any security, or a guarantee of future performance. Always conduct your own due diligence before making investment decisions.";

const ACTION_PLAN_DISCLAIMER =
  "This action plan is a research framework, not personalized financial advice. FinDesk is not a licensed investment adviser. The entry zones, stop losses, and targets above are analytical reference points only — not recommendations. Consult a qualified financial professional before making any investment decisions.";

/**
 * Merges live market data with the AI-generated qualitative analysis into the
 * full report shape, then validates it against the shared API contract.
 */
export function buildReport(
  ticker: string,
  market: MarketData,
  ai: AiReportOutput,
): Omit<FullReport, "id" | "generatedAt"> {
  const report: FullReport = {
    id: 0,
    generatedAt: new Date().toISOString(),
    ticker,
    companyName: ai.companyName || market.companyName || `${ticker} Corp.`,
    sector: ai.sector,
    industry: ai.industry,
    overallRating: ai.overallRating,
    disclaimer: DISCLAIMER,
    snapshot: {
      description: ai.snapshot.description,
      marketCap: ai.snapshot.marketCap,
      price: market.price,
      change1d: market.change1d,
      change52w: market.change52w,
      peRatio: ai.snapshot.peRatio,
      eps: ai.snapshot.eps,
      revenue: ai.snapshot.revenue,
      employees: ai.snapshot.employees,
      headquarters: ai.snapshot.headquarters,
      founded: ai.snapshot.founded,
      exchange: market.exchange ?? "—",
    },
    catalysts: ai.catalysts,
    news: {
      isPlaceholder: true,
      sentiment: ai.news.sentiment,
      headlines: ai.news.headlines,
    },
    filings: {
      isPlaceholder: true,
      lastForm10K: ai.filings.lastForm10K,
      lastForm10Q: ai.filings.lastForm10Q,
      keyHighlights: ai.filings.keyHighlights,
    },
    financials: {
      isPlaceholder: false,
      ...ai.financials,
    },
    valuation: {
      isPlaceholder: false,
      currentPrice: market.price,
      intrinsicValueLow: ai.valuation.intrinsicValueLow,
      intrinsicValueHigh: ai.valuation.intrinsicValueHigh,
      peComparison: ai.valuation.peComparison,
      evEbitda: ai.valuation.evEbitda,
      priceToBook: ai.valuation.priceToBook,
      priceToSales: ai.valuation.priceToSales,
      dcfNotes: ai.valuation.dcfNotes,
      comparables: ai.valuation.comparables,
    },
    technical: {
      isPlaceholder: false,
      trend: market.technical.trend,
      rsi: market.technical.rsi,
      macd: ai.technical.macd,
      supportLevel: market.technical.supportLevel,
      resistanceLevel: market.technical.resistanceLevel,
      ma50: market.technical.ma50,
      ma200: market.technical.ma200,
      goldenCross: market.technical.goldenCross,
      notes: ai.technical.notes,
    },
    risks: ai.risks,
    thesis: ai.thesis,
    actionPlan: {
      rating: ai.overallRating,
      rationale: ai.actionPlan.rationale,
      positionSizing: ai.actionPlan.positionSizing,
      entryZone: ai.actionPlan.entryZone,
      stopLoss: ai.actionPlan.stopLoss,
      profitTarget: ai.actionPlan.profitTarget,
      timeHorizon: ai.actionPlan.timeHorizon,
      keyMonitors: ai.actionPlan.keyMonitors,
      disclaimer: ACTION_PLAN_DISCLAIMER,
    },
  };

  const validated = GetReportResponse.parse(report);
  const { id: _id, generatedAt: _generatedAt, ...rest } = validated;
  return rest;
}
