export function generateMockReport(ticker: string, id: number) {
  const tickerUpper = ticker.toUpperCase();

  const companyMap: Record<string, { name: string; sector: string; industry: string; description: string; exchange: string; hq: string; founded: string; employees: string }> = {
    AAPL: { name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics", exchange: "NASDAQ", hq: "Cupertino, CA", founded: "1976", employees: "164,000", description: "Apple designs, manufactures and markets consumer electronics, software, and online services. Its ecosystem of iPhone, Mac, iPad, Apple Watch, and services generates among the highest margins in consumer tech." },
    MSFT: { name: "Microsoft Corporation", sector: "Technology", industry: "Software", exchange: "NASDAQ", hq: "Redmond, WA", founded: "1975", employees: "221,000", description: "Microsoft is a global software and cloud leader. Azure is the company's fastest-growing segment, with Copilot integration across Office 365, Dynamics, and GitHub accelerating enterprise AI adoption." },
    NVDA: { name: "NVIDIA Corporation", sector: "Technology", industry: "Semiconductors", exchange: "NASDAQ", hq: "Santa Clara, CA", founded: "1993", employees: "29,600", description: "NVIDIA designs AI accelerators, GPUs, and data center platforms. Its H100 and upcoming Blackwell chips are the de facto standard for large-scale AI training, giving NVDA dominant pricing power." },
    TSLA: { name: "Tesla, Inc.", sector: "Consumer Discretionary", industry: "Auto Manufacturers", exchange: "NASDAQ", hq: "Austin, TX", founded: "2003", employees: "140,000", description: "Tesla designs and manufactures electric vehicles, energy storage systems, and solar products. Full Self-Driving software and Optimus humanoid robot represent optionality beyond core automotive." },
    AMZN: { name: "Amazon.com, Inc.", sector: "Consumer Discretionary", industry: "Internet Retail", exchange: "NASDAQ", hq: "Seattle, WA", founded: "1994", employees: "1,550,000", description: "Amazon operates the world's largest e-commerce marketplace and the leading cloud infrastructure platform (AWS). Advertising is its fastest-growing, highest-margin segment." },
    GOOGL: { name: "Alphabet Inc.", sector: "Communication Services", industry: "Internet Content", exchange: "NASDAQ", hq: "Mountain View, CA", founded: "1998", employees: "181,000", description: "Alphabet's Google unit dominates search, YouTube, and the global digital advertising duopoly alongside Meta. DeepMind, Waymo, and Google Cloud represent significant long-term call options." },
    META: { name: "Meta Platforms, Inc.", sector: "Communication Services", industry: "Internet Content", exchange: "NASDAQ", hq: "Menlo Park, CA", founded: "2004", employees: "67,000", description: "Meta owns Facebook, Instagram, and WhatsApp — reaching 3.2B+ daily users. Its AI Advantage+ ads and Llama models are driving revenue acceleration while Reality Labs burns cash on the metaverse bet." },
    JPM: { name: "JPMorgan Chase & Co.", sector: "Financials", industry: "Diversified Banks", exchange: "NYSE", hq: "New York, NY", founded: "1799", employees: "311,000", description: "JPMorgan is the largest U.S. bank by assets. Its diversified model across investment banking, consumer banking, asset management, and markets makes it the benchmark large-cap financial." },
  };

  const company = companyMap[tickerUpper] ?? {
    name: `${tickerUpper} Corp.`,
    sector: "Technology",
    industry: "Software",
    exchange: "NASDAQ",
    hq: "San Francisco, CA",
    founded: "2010",
    employees: "12,000",
    description: `${tickerUpper} is a publicly traded company operating in the technology sector. This report is based on publicly available information and quantitative modeling.`,
  };

  const basePrice = 100 + (ticker.charCodeAt(0) * 7.3 + ticker.charCodeAt(ticker.length - 1) * 3.1) % 400;
  const price = Math.round(basePrice * 100) / 100;
  const change1d = Math.round((Math.random() * 4 - 2) * 100) / 100;
  const change52w = Math.round((Math.random() * 60 - 20) * 100) / 100;

  const ratings = ["BUY", "HOLD", "SELL", "WATCH"];
  // Deterministic placeholder (was Math.random() — a coin-flip verdict persisted as if real).
  // Stable per ticker so the same name never yields a different "verdict" between runs. This is
  // NOT a real signal; reports carry source='mock' so nothing downstream treats it as one.
  const rating = ratings[(ticker.charCodeAt(0) + ticker.charCodeAt(ticker.length - 1)) % 3];

  return {
    id,
    ticker: tickerUpper,
    companyName: company.name,
    sector: company.sector,
    industry: company.industry,
    generatedAt: new Date().toISOString(),
    overallRating: rating,
    disclaimer: "This report is generated by FinDesk AI and is for informational and research support purposes only. It does not constitute licensed financial advice, a solicitation to buy or sell any security, or a guarantee of future performance. Always conduct your own due diligence before making investment decisions.",
    snapshot: {
      description: company.description,
      marketCap: `$${(price * (2.5 + Math.random() * 10)).toFixed(1)}B`,
      price,
      change1d,
      change52w,
      peRatio: Math.round((15 + Math.random() * 50) * 10) / 10,
      eps: Math.round((price / (15 + Math.random() * 30)) * 100) / 100,
      revenue: `$${(15 + Math.random() * 200).toFixed(1)}B`,
      employees: company.employees,
      headquarters: company.hq,
      founded: company.founded,
      exchange: company.exchange,
    },
    catalysts: {
      positive: [
        "Strong free cash flow generation enabling continued buybacks and dividends",
        "AI integration accelerating across core product lines",
        "Expanding international market share in high-growth regions",
        "Margin expansion driven by operational efficiency programs",
      ],
      negative: [
        "Rising competition from well-funded domestic and foreign rivals",
        "Regulatory headwinds in EU and U.S. markets",
        "Macro sensitivity — discretionary exposure to consumer slowdown",
      ],
      upcoming: [
        `Q${Math.ceil(new Date().getMonth() / 3)} Earnings Call — ~${new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()}`,
        "Annual Investor Day — Q4 2025",
        "Potential M&A announcement — management has signaled acquisition appetite",
        "New product launch event — H2 2025",
      ],
    },
    news: {
      isPlaceholder: true,
      sentiment: "Neutral",
      headlines: [
        { title: `${company.name} beats Q3 estimates on strong cloud and services revenue`, source: "Reuters", date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], sentiment: "Bullish" },
        { title: `Analyst upgrades ${tickerUpper} to Overweight, raises price target to $${Math.round(price * 1.25)}`, source: "Bloomberg", date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], sentiment: "Bullish" },
        { title: `${company.name} faces antitrust inquiry from EU regulators over market dominance`, source: "FT", date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], sentiment: "Bearish" },
        { title: `${tickerUpper} CFO comments on FX headwinds at industry conference`, source: "WSJ", date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], sentiment: "Neutral" },
        { title: `Institutional investors increase ${tickerUpper} position by 12% in Q3 filings`, source: "SEC EDGAR", date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], sentiment: "Bullish" },
      ],
    },
    filings: {
      isPlaceholder: true,
      lastForm10K: "2024-10-28",
      lastForm10Q: "2025-02-03",
      keyHighlights: [
        "Management reiterated long-term revenue growth target of 12–15% CAGR",
        "Share repurchase authorization expanded to $90B — signals confidence in cash position",
        "Goodwill impairment risk flagged in recent acquisition — management monitoring",
        "Deferred revenue balance grew 22% YoY — strong forward-bookings signal",
        "R&D as % of revenue increased to 18% — heavy investment in next-gen platform",
      ],
    },
    financials: {
      isPlaceholder: false,
      revenueGrowthYoY: Math.round((5 + Math.random() * 25) * 10) / 10,
      grossMargin: Math.round((35 + Math.random() * 40) * 10) / 10,
      operatingMargin: Math.round((15 + Math.random() * 30) * 10) / 10,
      netMargin: Math.round((10 + Math.random() * 25) * 10) / 10,
      debtToEquity: Math.round((0.2 + Math.random() * 2) * 100) / 100,
      currentRatio: Math.round((1.1 + Math.random() * 2) * 100) / 100,
      freeCashFlow: `$${(5 + Math.random() * 80).toFixed(1)}B`,
      revenueHistory: [
        { period: "FY2021", revenue: Math.round((50 + Math.random() * 200) * 10) / 10 },
        { period: "FY2022", revenue: Math.round((60 + Math.random() * 220) * 10) / 10 },
        { period: "FY2023", revenue: Math.round((70 + Math.random() * 240) * 10) / 10 },
        { period: "FY2024", revenue: Math.round((85 + Math.random() * 260) * 10) / 10 },
        { period: "FY2025E", revenue: Math.round((100 + Math.random() * 280) * 10) / 10 },
      ],
    },
    valuation: {
      isPlaceholder: false,
      currentPrice: price,
      intrinsicValueLow: Math.round(price * 0.85 * 100) / 100,
      intrinsicValueHigh: Math.round(price * 1.35 * 100) / 100,
      peComparison: `${tickerUpper} trades at a ${Math.round(5 + Math.random() * 25)}% premium to sector median P/E of ${Math.round(18 + Math.random() * 15)}x, reflecting quality premium and AI optionality.`,
      evEbitda: Math.round((12 + Math.random() * 28) * 10) / 10,
      priceToBook: Math.round((2 + Math.random() * 15) * 10) / 10,
      priceToSales: Math.round((3 + Math.random() * 12) * 10) / 10,
      dcfNotes: `DCF at 10% WACC and 3% terminal growth yields a range of $${Math.round(price * 0.85)}–$${Math.round(price * 1.35)} per share. Key assumption sensitivity: each 1% change in terminal growth shifts fair value by ~$${Math.round(price * 0.08)}.`,
      comparables: [
        { ticker: "MSFT", pe: 31.2, evEbitda: 22.1 },
        { ticker: "GOOGL", pe: 24.8, evEbitda: 16.4 },
        { ticker: "META", pe: 27.3, evEbitda: 18.9 },
        { ticker: tickerUpper !== "AAPL" ? "AAPL" : "AMZN", pe: 28.5, evEbitda: 21.3 },
      ].filter(c => c.ticker !== tickerUpper),
    },
    technical: {
      isPlaceholder: true,
      trend: Math.random() > 0.5 ? "Bullish" : "Mixed",
      rsi: Math.round((42 + Math.random() * 30) * 10) / 10,
      macd: Math.random() > 0.5 ? "Bullish crossover" : "Bearish crossover",
      supportLevel: Math.round(price * 0.88 * 100) / 100,
      resistanceLevel: Math.round(price * 1.12 * 100) / 100,
      ma50: Math.round(price * (0.93 + Math.random() * 0.1) * 100) / 100,
      ma200: Math.round(price * (0.82 + Math.random() * 0.15) * 100) / 100,
      goldenCross: Math.random() > 0.5,
      notes: `Price is ${Math.random() > 0.5 ? "above" : "approaching"} the 200-day moving average. Volume trend suggests accumulation. RSI is ${Math.random() > 0.5 ? "approaching overbought territory" : "in neutral range"}. Technical setup warrants caution near resistance.`,
    },
    risks: {
      items: [
        { category: "Macro", description: "Sustained high interest rates compress growth multiples and increase the cost of capital for future investments", severity: "Medium" },
        { category: "Regulatory", description: "Ongoing EU Digital Markets Act compliance obligations may require product changes affecting monetization", severity: "Medium" },
        { category: "Competition", description: "Well-capitalized competitors with AI-first positioning are compressing market share in core segments", severity: "High" },
        { category: "Execution", description: "Integration of recent acquisitions carries operational risk; synergy timelines may slip", severity: "Low" },
        { category: "FX / Macro", description: "Strong USD creates headwinds on international revenue translation (~40% of total sales)", severity: "Medium" },
        { category: "Concentration", description: "Top 5 customers represent significant revenue concentration — churn risk is non-trivial", severity: "Low" },
        { category: "Valuation", description: "Premium multiple relative to peers leaves limited margin for error on earnings misses", severity: "High" },
      ],
    },
    thesis: {
      bull: {
        targetPrice: Math.round(price * 1.45 * 100) / 100,
        probability: 30,
        summary: "AI monetization exceeds expectations; multiple expansion as the market rewards sustained double-digit growth",
        points: [
          "AI-powered products drive 20%+ revenue acceleration in FY2026",
          "Operating margin expands 300bps through automation and cost discipline",
          "Multiple re-rates to 35x earnings on sustained growth credibility",
          "Capital return program adds 2-3% annual shareholder yield",
        ],
      },
      base: {
        targetPrice: Math.round(price * 1.15 * 100) / 100,
        probability: 50,
        summary: "Steady compounding; in-line revenue growth with modest margin improvement and sustained capital return",
        points: [
          "Revenue grows 10–14% annually, consistent with recent trend",
          "Margins stable to slightly expanding — no major cost surprises",
          "Multiple stays range-bound; stock tracks earnings growth",
          "M&A optionality creates small positive surprise potential",
        ],
      },
      bear: {
        targetPrice: Math.round(price * 0.72 * 100) / 100,
        probability: 20,
        summary: "Macro deterioration and competitive pressure compress margins; multiple contracts sharply",
        points: [
          "Revenue growth decelerates below 5% on macro/competitive pressure",
          "Operating margins compress 200bps+ due to rising R&D and SG&A",
          "Multiple de-rates to sector average (~18–20x) on growth concerns",
          "Regulatory fines or product bans in key markets create one-time headwinds",
        ],
      },
    },
    actionPlan: {
      rating,
      rationale: `Based on the bull/base/bear analysis and current valuation, ${tickerUpper} appears ${rating === "BUY" ? "attractively priced relative to intrinsic value with a favorable risk/reward skew" : rating === "HOLD" ? "fairly valued with limited near-term upside; accumulating on weakness is a reasonable approach" : rating === "SELL" ? "richly valued given near-term execution risks — reducing exposure is warranted" : "worth monitoring for a better entry point before establishing a position"}.`,
      positionSizing: "Research framework suggests sizing consistent with position conviction and individual portfolio risk tolerance. This model does not prescribe specific portfolio weights.",
      entryZone: `$${Math.round(price * 0.93 * 100) / 100} – $${Math.round(price * 0.98 * 100) / 100} (current area or on pullback to support)`,
      stopLoss: `$${Math.round(price * 0.85 * 100) / 100} (below 200-day moving average / key support level)`,
      profitTarget: `$${Math.round(price * 1.25 * 100) / 100} (base case) | $${Math.round(price * 1.45 * 100) / 100} (bull case)`,
      timeHorizon: "12–18 months (medium-term position)",
      keyMonitors: [
        "Quarterly earnings — particularly revenue growth rate and operating margin trajectory",
        "AI product adoption metrics and monetization evidence in earnings commentary",
        "Competitive announcements from key rivals — monitor market share data",
        "Regulatory developments in EU and U.S. — any fines or consent decrees",
        "Macro indicators — Fed rate path, consumer spending data, enterprise IT budgets",
      ],
      disclaimer: "This action plan is a research framework, not personalized financial advice. FinDesk is not a licensed investment adviser. The entry zones, stop losses, and targets above are analytical reference points only — not recommendations. Consult a qualified financial professional before making any investment decisions.",
    },
  };
}
